// alert('Hallo')
// console.log ('My name is Yudi.')

// let usia = prompt('Masukan usia anda!')
// console.log('Hello Usia kamu Adalah ' + usia)
// alert('Hello Usia kamu Adalah ' + usia)

let nama = prompt('Mausukan Nama Anda!')
let usia = prompt('Mausukan Usia Anda!')
let TB = prompt('Mausukan Tiggi Badan Anda!')
let BB = prompt('Mausukan Berat Badan Anda!')
let pasangan = alert('Jomblo!! XIXIXIXI')
pasangan = 'Tra ada'

alert('Nama anda adalah ' + nama +
     ', usia anda adalah '+ usia + 
     ', tiggi badan anda adalah ' + TB +
      ', barat badan anda adalah ' + BB +
       ' dan pasangan anda adalah ' + pasangan)
console.log('Nama anda adalah ' + nama+
    ', usia anda adalah '+ usia +
    ', tiggi badan anda adalah ' + TB +
    ', barat badan anda adalah ' + BB +
    ' dan pasangan anda adalah ' + pasangan)